# -*- coding: utf-8 -*-
"""Expanded major catalog with subject-track eligibility (物理类/历史类).

Each entry:
  name, discipline, subjects, tier, manualTrend, trendRationale, opportunity?
manualTrend: 0-100 expert/industry manual score (policy + demand narrative).
subjects: which gaokao tracks may apply — 物理类 (理科) / 历史类 (文科).
"""

from __future__ import annotations

from typing import Any

# fmt: off
CATALOG_ENTRIES: list[dict[str, Any]] = [
    # ── 物理类 · 工科 / 理科 ──
    {"name": "人工智能", "discipline": "工科", "subjects": ["物理类"], "tier": "985", "manualTrend": 98,
     "trendRationale": "AI 产业化与算力需求持续扩张，算法与应用岗位长期紧缺"},
    {"name": "集成电路设计与集成系统", "discipline": "工科", "subjects": ["物理类"], "tier": "985", "manualTrend": 97,
     "trendRationale": "芯片自主化战略驱动设计、验证、制造人才需求"},
    {"name": "机器人工程", "discipline": "工科", "subjects": ["物理类"], "tier": "211", "manualTrend": 96,
     "trendRationale": "智能制造与服务机器人场景持续增加"},
    {"name": "软件工程", "discipline": "工科", "subjects": ["物理类"], "tier": "211", "manualTrend": 95,
     "trendRationale": "数字化与 AI 应用落地依赖软件交付能力"},
    {"name": "数据科学与大数据技术", "discipline": "工科", "subjects": ["物理类"], "tier": "211", "manualTrend": 94,
     "trendRationale": "企业数据治理与商业智能岗位稳定增长"},
    {"name": "网络空间安全", "discipline": "工科", "subjects": ["物理类"], "tier": "211", "manualTrend": 93,
     "trendRationale": "合规与攻防需求叠加，安全人才缺口持续"},
    {"name": "新能源科学与工程", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 92,
     "trendRationale": "双碳政策下储能、光伏、电网改造长期投入"},
    {"name": "电气工程及其自动化", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 91,
     "trendRationale": "新型电力系统与工业电气化带动岗位"},
    {"name": "自动化", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 90,
     "trendRationale": "工控、流程工业与智能产线维护需求稳定"},
    {"name": "电子信息工程", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 89,
     "trendRationale": "通信、物联网、汽车电子等多场景交叉"},
    {"name": "计算机科学与技术", "discipline": "工科", "subjects": ["物理类"], "tier": "211", "manualTrend": 93,
     "trendRationale": "通用计算机能力仍是数字经济底座"},
    {"name": "物联网工程", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 86,
     "trendRationale": "产业物联网与智慧城市场景扩张"},
    {"name": "机械设计制造及其自动化", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 82,
     "trendRationale": "先进制造与设备更新带来稳定技工/工程师需求"},
    {"name": "材料科学与工程", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 80,
     "trendRationale": "新材料产业链国产替代持续推进"},
    {"name": "测控技术与仪器", "discipline": "工科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 78,
     "trendRationale": "高端装备检测与仪器仪表需求稳健"},
    {"name": "临床医学", "discipline": "医科", "subjects": ["物理类"], "tier": "211", "manualTrend": 88,
     "trendRationale": "医疗刚需+专科规培体系，岗位长期稳定"},
    {"name": "口腔医学", "discipline": "医科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 84,
     "trendRationale": "民营口腔连锁扩张，执业路径清晰"},
    {"name": "生物医学工程", "discipline": "理科", "subjects": ["物理类"], "tier": "211", "manualTrend": 87,
     "trendRationale": "医疗器械与医工交叉岗位增长"},
    {"name": "统计学", "discipline": "理科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 86,
     "trendRationale": "数据分析岗位向理工背景倾斜"},
    {"name": "数学与应用数学", "discipline": "理科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 85,
     "trendRationale": "量化、算法、金融工程等的基础学科"},
    {"name": "物理学", "discipline": "理科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 72,
     "trendRationale": "基础研究+半导体/光学等应用出口需提前规划"},
    {"name": "化学", "discipline": "理科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 74,
     "trendRationale": "化工、新能源材料、制药研发等应用方向"},
    {"name": "药学", "discipline": "医科", "subjects": ["物理类"], "tier": "一本", "manualTrend": 80,
     "trendRationale": "创新药与 CXO 产业链带动研发岗位"},

    # ── 历史类 · 文科 / 商科 / 艺术 ──
    {"name": "法学", "discipline": "文科", "subjects": ["历史类"], "tier": "211", "manualTrend": 80,
     "trendRationale": "法治社会刚需；红圈/法务合规出口分化大，需院校与实习背书"},
    {"name": "汉语言文学", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 76,
     "trendRationale": "考公、教育、内容产业基础面广"},
    {"name": "英语", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 74,
     "trendRationale": "跨境贸易、外企、翻译+复合技能仍有空间"},
    {"name": "新闻学", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 72,
     "trendRationale": "新媒体运营、品牌传播岗位多于传统采编"},
    {"name": "传播学", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 73,
     "trendRationale": "短视频、公关、用户增长等应用型岗位"},
    {"name": "历史学", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 65,
     "trendRationale": "文博、教育、公务员等方向，需早做职业规划"},
    {"name": "思想政治教育", "discipline": "文科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 68,
     "trendRationale": "思政教师、党务、事业单位等稳定出口"},
    {"name": "行政管理", "discipline": "文科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 70,
     "trendRationale": "公务员、事业单位、企业行政综合岗"},
    {"name": "社会工作", "discipline": "文科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 69,
     "trendRationale": "社区治理、公益、民政相关岗位稳步增加"},
    {"name": "教育学", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 71,
     "trendRationale": "教师编、培训机构管理，受政策周期影响"},
    {"name": "学前教育", "discipline": "文科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 72,
     "trendRationale": "托育与素质教育政策支撑基本需求"},
    {"name": "心理学", "discipline": "文科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 75,
     "trendRationale": "学校心理、EAP、用户体验研究等交叉岗位"},
    {"name": "会计学", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 83,
     "trendRationale": "财务共享、审计、税务岗位需求稳定"},
    {"name": "财务管理", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 81,
     "trendRationale": "企业财管、投融资分析、内控岗位"},
    {"name": "国际经济与贸易", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 77,
     "trendRationale": "跨境电商、外贸综合服务仍有区域机会"},
    {"name": "电子商务", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 81,
     "trendRationale": "直播电商与跨境贸易运营岗位活跃"},
    {"name": "数字经济", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 82,
     "trendRationale": "产业数字化咨询、运营、产品岗位"},
    {"name": "旅游管理", "discipline": "商科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 68,
     "trendRationale": "文旅复苏与本地生活服务带动运营岗"},
    {"name": "酒店管理", "discipline": "商科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 66,
     "trendRationale": "高端服务业管理岗，地域与品牌差异大"},
    {"name": "视觉传达设计", "discipline": "艺术", "subjects": ["历史类"], "tier": "一本", "manualTrend": 76,
     "trendRationale": "品牌、电商视觉、自媒体设计需求持续"},
    {"name": "数字媒体艺术", "discipline": "艺术", "subjects": ["历史类"], "tier": "一本", "manualTrend": 77,
     "trendRationale": "短视频、游戏、AIGC 视觉制作场景"},
    {"name": "广播电视编导", "discipline": "艺术", "subjects": ["历史类"], "tier": "一本", "manualTrend": 74,
     "trendRationale": "综艺、短视频、MCN 内容制作链"},
    {"name": "动画", "discipline": "艺术", "subjects": ["历史类"], "tier": "一本", "manualTrend": 73,
     "trendRationale": "游戏、影视、广告动效岗位"},

    # ── 文理均可 / 交叉商科 ──
    {"name": "金融工程", "discipline": "商科", "subjects": ["物理类"], "tier": "211", "manualTrend": 84,
     "trendRationale": "量化、风控、金融科技偏理工背景"},
    {"name": "经济学", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 78,
     "trendRationale": "宏观研究、银行、咨询等需名校/深造加持"},
    {"name": "金融学", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 79,
     "trendRationale": "银行、券商、资管等传统金融岗位竞争加剧"},
    {"name": "工商管理", "discipline": "商科", "subjects": ["历史类"], "tier": "一本", "manualTrend": 72,
     "trendRationale": "管培、运营、销售管理，院校与实习决定差异"},
    {"name": "市场营销", "discipline": "商科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 73,
     "trendRationale": "品牌、增长、电商运营等应用岗"},
    {"name": "物流管理", "discipline": "商科", "subjects": ["历史类"], "tier": "二本", "manualTrend": 74,
     "trendRationale": "供应链数字化推动计划与协调岗位"},

    # ── 医科 · 文理分轨 ──
    {"name": "护理学", "discipline": "医科", "subjects": ["物理类", "历史类"], "tier": "二本", "manualTrend": 89,
     "trendRationale": "老龄化与医养结合，护理岗位长期紧缺", "opportunity": True},
    {"name": "康复治疗学", "discipline": "医科", "subjects": ["物理类", "历史类"], "tier": "二本", "manualTrend": 86,
     "trendRationale": "康复医疗与运动康复市场稳步增长"},

    # ── 二本机会点（物理类）──
    {"name": "软件工程", "discipline": "工科", "subjects": ["物理类"], "tier": "二本", "manualTrend": 95,
     "trendRationale": "应用型软件人才在产业下沉市场缺口大", "opportunity": True, "entryKey": "软件工程@二本"},
    {"name": "电气工程及其自动化", "discipline": "工科", "subjects": ["物理类"], "tier": "二本", "manualTrend": 91,
     "trendRationale": "电网改造与智能制造带动需求", "opportunity": True, "entryKey": "电气工程及其自动化@二本"},
    {"name": "土木工程", "discipline": "工科", "subjects": ["物理类"], "tier": "二本", "manualTrend": 74,
     "trendRationale": "市政更新与基建维护提供稳定岗位"},

    # ── 专科 · 物理类 ──
    {"name": "大数据技术", "discipline": "工科", "subjects": ["物理类"], "tier": "专科", "manualTrend": 90,
     "trendRationale": "数据岗位高职化，实操型人才需求上升", "opportunity": True},
    {"name": "新能源汽车技术", "discipline": "工科", "subjects": ["物理类"], "tier": "专科", "manualTrend": 92,
     "trendRationale": "电动化产业链持续扩招技工", "opportunity": True},
    {"name": "计算机网络技术", "discipline": "工科", "subjects": ["物理类"], "tier": "专科", "manualTrend": 88,
     "trendRationale": "运维、网络安全、云服务岗位稳定", "opportunity": True},
    {"name": "机电一体化技术", "discipline": "工科", "subjects": ["物理类"], "tier": "专科", "manualTrend": 87,
     "trendRationale": "先进制造设备维护刚需"},
    {"name": "口腔医学技术", "discipline": "医科", "subjects": ["物理类"], "tier": "专科", "manualTrend": 85,
     "trendRationale": "口腔技师与义齿数字化岗位"},
    {"name": "建筑工程技术", "discipline": "工科", "subjects": ["物理类"], "tier": "专科", "manualTrend": 76,
     "trendRationale": "市政与装修工程技术岗位"},
    {"name": "现代物流管理", "discipline": "商科", "subjects": ["物理类", "历史类"], "tier": "专科", "manualTrend": 80,
     "trendRationale": "智慧仓储与供应链协调岗", "opportunity": True},

    # ── 专科 · 历史类 ──
    {"name": "电子商务", "discipline": "商科", "subjects": ["历史类"], "tier": "专科", "manualTrend": 81,
     "trendRationale": "高职电商运营、直播带货岗位", "opportunity": True, "entryKey": "电子商务@专科"},
    {"name": "大数据与会计", "discipline": "商科", "subjects": ["历史类"], "tier": "专科", "manualTrend": 78,
     "trendRationale": "财务数字化+中小企业会计岗"},
    {"name": "旅游管理", "discipline": "商科", "subjects": ["历史类"], "tier": "专科", "manualTrend": 68,
     "trendRationale": "文旅服务、景区运营、民宿管理", "entryKey": "旅游管理@专科"},
    {"name": "学前教育", "discipline": "文科", "subjects": ["历史类"], "tier": "专科", "manualTrend": 72,
     "trendRationale": "托育机构教师与保育员需求", "entryKey": "学前教育@专科"},
    {"name": "社会工作", "discipline": "文科", "subjects": ["历史类"], "tier": "专科", "manualTrend": 69,
     "trendRationale": "社区服务、民政基层岗位", "entryKey": "社会工作@专科"},
    {"name": "新闻采编与制作", "discipline": "文科", "subjects": ["历史类"], "tier": "专科", "manualTrend": 70,
     "trendRationale": "新媒体内容制作、短视频编导"},
]
# fmt: on
